// Code generated by "stringer -type=BinaryKind -linecomment"; DO NOT EDIT.

package xql

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KindBinary-0]
	_ = x[KindBinaryVarying-1]
	_ = x[KindVarBinary-2]
	_ = x[KindBigLargeObject-3]
	_ = x[KindBlob-4]
}

const _BinaryKind_name = "BINARYBINARY VARYINGVARBINARYBINARY LARGE OBJECTBLOB"

var _BinaryKind_index = [...]uint8{0, 6, 20, 29, 48, 52}

func (i BinaryKind) String() string {
	if i < 0 || i >= BinaryKind(len(_BinaryKind_index)-1) {
		return "BinaryKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BinaryKind_name[_BinaryKind_index[i]:_BinaryKind_index[i+1]]
}
