// Code generated by "stringer -type=BoolKind -linecomment"; DO NOT EDIT.

package xql

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KindBoolean-0]
	_ = x[KindBit-1]
}

const _BoolKind_name = "BOOLEANBIT"

var _BoolKind_index = [...]uint8{0, 7, 10}

func (i BoolKind) String() string {
	if i < 0 || i >= BoolKind(len(_BoolKind_index)-1) {
		return "BoolKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BoolKind_name[_BoolKind_index[i]:_BoolKind_index[i+1]]
}
