// Code generated by "stringer -type=CharKind -linecomment"; DO NOT EDIT.

package xql

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KindCharacter-0]
	_ = x[KindChar-1]
	_ = x[KindCharacterVarying-2]
	_ = x[KindCharVarying-3]
	_ = x[KindVarChar-4]
	_ = x[KindCharacterLargeObject-5]
	_ = x[KindCharLargeObject-6]
	_ = x[KindClob-7]
	_ = x[KindText-8]
	_ = x[KindNationalCharacter-9]
	_ = x[KindNationalChar-10]
	_ = x[KindNChar-11]
	_ = x[KindNationalCharacterVarying-12]
	_ = x[KindNationalCharVarying-13]
	_ = x[KindNCharVarying-14]
	_ = x[KindNationalCharacterLargeObject-15]
	_ = x[KindNCharLargeObject-16]
	_ = x[KindNClob-17]
}

const _CharKind_name = "CHARACTERCHARCHARACTER VARYINGCHAR VARYINGVARCHARCHARACTER LARGE OBJECTCHAR LARGE OBJECTCLOBTEXTNATIONAL CHARACTERNATIONAL CHARNCHARNATIONAL CHARACTER VARYINGNATIONAL CHAR VARYINGNCHAR VARYINGNATIONAL CHARACTER LARGE OBJECTNCHAR LARGE OBJECTNCLOB"

var _CharKind_index = [...]uint8{0, 9, 13, 30, 42, 49, 71, 88, 92, 96, 114, 127, 132, 158, 179, 192, 223, 241, 246}

func (i CharKind) String() string {
	if i < 0 || i >= CharKind(len(_CharKind_index)-1) {
		return "CharKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CharKind_name[_CharKind_index[i]:_CharKind_index[i+1]]
}
