// Code generated by "stringer -type=CharLengthUnit -linecomment"; DO NOT EDIT.

package xql

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnitChars-0]
	_ = x[UnitOctets-1]
	_ = x[UnitCodeUnits32-2]
}

const _CharLengthUnit_name = "CHARACTERSOCTETSCODEUNITS32"

var _CharLengthUnit_index = [...]uint8{0, 10, 16, 27}

func (i CharLengthUnit) String() string {
	if i < 0 || i >= CharLengthUnit(len(_CharLengthUnit_index)-1) {
		return "CharLengthUnit(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CharLengthUnit_name[_CharLengthUnit_index[i]:_CharLengthUnit_index[i+1]]
}
