package xql_test

import (
	"fmt"

	. "github.com/flier/xql"
)

func ExampleColumnDef() {
	fmt.Println(Column("code", Char(5), Constraint("firstkey").PrimaryKey()))
	fmt.Println(Column("title", VarChar(40), NotNull))
	fmt.Println(Column("len", Hour.To(Minute)))
	fmt.Println(Column("did", Integer, PrimaryKey, Generated.ByDefault().AsIdentity()))
	fmt.Println(Column("name", VarChar(40), NotNull, Check(Raw("name <> ''"))))
	fmt.Println(Column("name", VarChar(40), Raw("nextval('distributors_serial')").AsDefault()))
	fmt.Println(Column("modtime", Timestamp, CurrentTimestamp.AsDefault()))
	// Output:
	// code CHAR(5) CONSTRAINT firstkey PRIMARY KEY
	// title VARCHAR(40) NOT NULL
	// len INTERVAL HOUR TO MINUTE
	// did INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
	// name VARCHAR(40) NOT NULL CHECK (name <> '')
	// name VARCHAR(40) DEFAULT nextval('distributors_serial')
	// modtime TIMESTAMP DEFAULT CURRENT_TIMESTAMP
}
