// Code generated by "stringer -type=ConstraintCheckTime -linecomment"; DO NOT EDIT.

package xql

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CheckTimeInitiallyDeferred-0]
	_ = x[CheckTimeInitiallyImmediate-1]
}

const _ConstraintCheckTime_name = "INITIALLY DEFERREDINITIALLY IMMEDIATE"

var _ConstraintCheckTime_index = [...]uint8{0, 18, 37}

func (i ConstraintCheckTime) String() string {
	if i < 0 || i >= ConstraintCheckTime(len(_ConstraintCheckTime_index)-1) {
		return "ConstraintCheckTime(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ConstraintCheckTime_name[_ConstraintCheckTime_index[i]:_ConstraintCheckTime_index[i+1]]
}
