// Code generated by "stringer -type=DateTimeValueKind -linecomment"; DO NOT EDIT.

package xql

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KindCurrentDate-0]
	_ = x[KindCurrentTime-1]
	_ = x[KindLocalTime-2]
	_ = x[KindCurrentTimestamp-3]
	_ = x[KindLocalTimestamp-4]
}

const _DateTimeValueKind_name = "CURRENT_DATECURRENT_TIMELOCALTIMECURRENT_TIMESTAMPLOCALTIMESTAMP"

var _DateTimeValueKind_index = [...]uint8{0, 12, 24, 33, 50, 64}

func (i DateTimeValueKind) String() string {
	if i < 0 || i >= DateTimeValueKind(len(_DateTimeValueKind_index)-1) {
		return "DateTimeValueKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DateTimeValueKind_name[_DateTimeValueKind_index[i]:_DateTimeValueKind_index[i+1]]
}
