// Code generated by "stringer -type=DefaultKind -linecomment"; DO NOT EDIT.

package xql

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DefaultUser-0]
	_ = x[DefaultCurrentUser-1]
	_ = x[DefaultCurrentRole-2]
	_ = x[DefaultSessionUser-3]
	_ = x[DefaultSystemUser-4]
	_ = x[DefaultCurrentCatalog-5]
	_ = x[DefaultCurrentSchema-6]
	_ = x[DefaultCurrentPath-7]
}

const _DefaultKind_name = "USERCURRENT_USERCURRENT_ROLESESSION_USERSYSTEM_USERCURRENT_CATALOGCURRENT_SCHEMACURRENT_PATH"

var _DefaultKind_index = [...]uint8{0, 4, 16, 28, 40, 51, 66, 80, 92}

func (i DefaultKind) String() string {
	if i < 0 || i >= DefaultKind(len(_DefaultKind_index)-1) {
		return "DefaultKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DefaultKind_name[_DefaultKind_index[i]:_DefaultKind_index[i+1]]
}
