// Code generated by "stringer -type=ForLockMode -linecomment"; DO NOT EDIT.

package xql

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ForUpdate-0]
	_ = x[ForNoKeyUpdate-1]
	_ = x[ForShare-2]
	_ = x[ForKeyShare-3]
}

const _ForLockMode_name = "UPDATENO KEY UPDATESHAREKEY SHARE"

var _ForLockMode_index = [...]uint8{0, 6, 19, 24, 33}

func (i ForLockMode) String() string {
	if i < 0 || i >= ForLockMode(len(_ForLockMode_index)-1) {
		return "ForLockMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ForLockMode_name[_ForLockMode_index[i]:_ForLockMode_index[i+1]]
}
