// Code generated by "stringer -type IdentityColumnRestart -linecomment"; DO NOT EDIT.

package xql

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ContinueIdentity-0]
	_ = x[RestartIdentity-1]
}

const _IdentityColumnRestart_name = "CONTINUE IDENTITYRESTART IDENTITY"

var _IdentityColumnRestart_index = [...]uint8{0, 17, 33}

func (i IdentityColumnRestart) String() string {
	if i < 0 || i >= IdentityColumnRestart(len(_IdentityColumnRestart_index)-1) {
		return "IdentityColumnRestart(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _IdentityColumnRestart_name[_IdentityColumnRestart_index[i]:_IdentityColumnRestart_index[i+1]]
}
