// Code generated by "stringer -type=IntKind -linecomment"; DO NOT EDIT.

package xql

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KindTinyInt-0]
	_ = x[KindSmallInt-1]
	_ = x[KindMediumInt-2]
	_ = x[KindInt-3]
	_ = x[KindInteger-4]
	_ = x[KindBigInt-5]
}

const _IntKind_name = "TINYINTSMALLINTMEDIUMINTINTINTEGERBIGINT"

var _IntKind_index = [...]uint8{0, 7, 15, 24, 27, 34, 40}

func (i IntKind) String() string {
	if i < 0 || i >= IntKind(len(_IntKind_index)-1) {
		return "IntKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _IntKind_name[_IntKind_index[i]:_IntKind_index[i+1]]
}
