// Code generated by "stringer -type=LikeAction -linecomment"; DO NOT EDIT.

package xql

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LikeExcluding-0]
	_ = x[LikeIncluding-1]
}

const _LikeAction_name = "EXCLUDINGINCLUDING"

var _LikeAction_index = [...]uint8{0, 9, 18}

func (i LikeAction) String() string {
	if i < 0 || i >= LikeAction(len(_LikeAction_index)-1) {
		return "LikeAction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LikeAction_name[_LikeAction_index[i]:_LikeAction_index[i+1]]
}
