// Code generated by "stringer -type=LikeProperty -linecomment"; DO NOT EDIT.

package xql

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LikeComments-0]
	_ = x[LikeCompression-1]
	_ = x[LikeConstraints-2]
	_ = x[LikeDefaults-3]
	_ = x[LikeGenerated-4]
	_ = x[LikeIdentity-5]
	_ = x[LikeIndexes-6]
	_ = x[LikeStatistics-7]
	_ = x[LikeStorage-8]
	_ = x[LikeAll-9]
}

const _LikeProperty_name = "COMMENTSCOMPRESSIONCONSTRAINTSDEFAULTSGENERATEDIDENTITYINDEXESSTATISTICSSTORAGEALL"

var _LikeProperty_index = [...]uint8{0, 8, 19, 30, 38, 47, 55, 62, 72, 79, 82}

func (i LikeProperty) String() string {
	if i < 0 || i >= LikeProperty(len(_LikeProperty_index)-1) {
		return "LikeProperty(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LikeProperty_name[_LikeProperty_index[i]:_LikeProperty_index[i+1]]
}
