// Code generated by "stringer -type=MatchType -linecomment"; DO NOT EDIT.

package xql

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MatchSimple-0]
	_ = x[MatchFull-1]
	_ = x[MatchPartial-2]
}

const _MatchType_name = "SIMPLEFULLPARTIAL"

var _MatchType_index = [...]uint8{0, 6, 10, 17}

func (i MatchType) String() string {
	if i < 0 || i >= MatchType(len(_MatchType_index)-1) {
		return "MatchType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MatchType_name[_MatchType_index[i]:_MatchType_index[i+1]]
}
