// Code generated by "stringer -type=NullOrdering -linecomment"; DO NOT EDIT.

package xql

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NullsFirst-0]
	_ = x[NullsLast-1]
}

const _NullOrdering_name = "NULLS FIRSTNULLS LAST"

var _NullOrdering_index = [...]uint8{0, 11, 21}

func (i NullOrdering) String() string {
	if i < 0 || i >= NullOrdering(len(_NullOrdering_index)-1) {
		return "NullOrdering(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NullOrdering_name[_NullOrdering_index[i]:_NullOrdering_index[i+1]]
}
