// Code generated by "stringer -type=OrderingSpec -linecomment"; DO NOT EDIT.

package xql

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OrderingAsc-0]
	_ = x[OrderingDesc-1]
}

const _OrderingSpec_name = "ASCDESC"

var _OrderingSpec_index = [...]uint8{0, 3, 7}

func (i OrderingSpec) String() string {
	if i < 0 || i >= OrderingSpec(len(_OrderingSpec_index)-1) {
		return "OrderingSpec(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OrderingSpec_name[_OrderingSpec_index[i]:_OrderingSpec_index[i+1]]
}
