// Code generated by "stringer -type OverridingClause -linecomment"; DO NOT EDIT.

package xql

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OverridingUserValue-0]
	_ = x[OverridingSystemValue-1]
}

const _OverridingClause_name = "OverridingUserValueOverridingSystemValue"

var _OverridingClause_index = [...]uint8{0, 19, 40}

func (i OverridingClause) String() string {
	if i < 0 || i >= OverridingClause(len(_OverridingClause_index)-1) {
		return "OverridingClause(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OverridingClause_name[_OverridingClause_index[i]:_OverridingClause_index[i+1]]
}
