// Code generated by "stringer -type=ReferentialAction -linecomment"; DO NOT EDIT.

package xql

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NoAction-0]
	_ = x[Cascade-1]
	_ = x[SetNull-2]
	_ = x[SetDefault-3]
	_ = x[Restrict-4]
}

const _ReferentialAction_name = "NO ACTIONCASCADESET NULLSET DEFAULTRESTRICT"

var _ReferentialAction_index = [...]uint8{0, 9, 16, 24, 35, 43}

func (i ReferentialAction) String() string {
	if i < 0 || i >= ReferentialAction(len(_ReferentialAction_index)-1) {
		return "ReferentialAction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ReferentialAction_name[_ReferentialAction_index[i]:_ReferentialAction_index[i+1]]
}
