// Code generated by "stringer -type SetQuantifier -linecomment"; DO NOT EDIT.

package xql

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SetAll-0]
	_ = x[SetDistinct-1]
	_ = x[SetDistinctRow-2]
}

const _SetQuantifier_name = "ALLDISTINCTDISTINCTROW"

var _SetQuantifier_index = [...]uint8{0, 3, 11, 22}

func (i SetQuantifier) String() string {
	if i < 0 || i >= SetQuantifier(len(_SetQuantifier_index)-1) {
		return "SetQuantifier(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SetQuantifier_name[_SetQuantifier_index[i]:_SetQuantifier_index[i+1]]
}
