// Code generated by "stringer -type=UniqueSpec -linecomment"; DO NOT EDIT.

package xql

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SpecUnique-0]
	_ = x[SpecPrimaryKey-1]
}

const _UniqueSpec_name = "UNIQUEPRIMARY KEY"

var _UniqueSpec_index = [...]uint8{0, 6, 17}

func (i UniqueSpec) String() string {
	if i < 0 || i >= UniqueSpec(len(_UniqueSpec_index)-1) {
		return "UniqueSpec(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UniqueSpec_name[_UniqueSpec_index[i]:_UniqueSpec_index[i+1]]
}
