// Code generated by "stringer -type WindowFrameUnits -linecomment"; DO NOT EDIT.

package xql

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnitRows-0]
	_ = x[UnitRange-1]
	_ = x[UnitGroups-2]
}

const _WindowFrameUnits_name = "ROWSRANGEGROUPS"

var _WindowFrameUnits_index = [...]uint8{0, 4, 9, 15}

func (i WindowFrameUnits) String() string {
	if i < 0 || i >= WindowFrameUnits(len(_WindowFrameUnits_index)-1) {
		return "WindowFrameUnits(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _WindowFrameUnits_name[_WindowFrameUnits_index[i]:_WindowFrameUnits_index[i+1]]
}
