// Code generated by "stringer -type WindowFrameExclusion -linecomment"; DO NOT EDIT.

package xql

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ExcludeCurrentRow-0]
	_ = x[ExcludeGroup-1]
	_ = x[ExcludeTies-2]
	_ = x[ExcludeNoOthers-3]
}

const _WindowFrameExclusion_name = "EXCLUDE CURRENT ROWEXCLUDE GROUPEXCLUDE TIESEXCLUDE NO OTHERS"

var _WindowFrameExclusion_index = [...]uint8{0, 19, 32, 44, 61}

func (i WindowFrameExclusion) String() string {
	if i < 0 || i >= WindowFrameExclusion(len(_WindowFrameExclusion_index)-1) {
		return "WindowFrameExclusion(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _WindowFrameExclusion_name[_WindowFrameExclusion_index[i]:_WindowFrameExclusion_index[i+1]]
}
